# Generated by Django 5.1.5 on 2025-01-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocument',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
